### ISSUE TITLE
Simplify repeated reduction ops in a chain into one

### ISSUE THREAD

**Issue by wjsi** [mars-project/mars#532] opened 2019-07-10 12:08 UTC
Tree reductions in Mars occasionally build operand chains like Reduction->Reduction for corners. This can be simplified by stopping creating reductions with one single inputs.

**Comment by qinxuye** [comment] 2019-11-15 07:43
For the reduction op like `sum`, the map phase and combine phase is all sum op, so although the ops look the same, but actually they may have different properties.

Besides, for those reduction op like `mean`, the chunk ops would be different, maybe `MeanChunk` and `MeanCombine` etc.

Thus, I think it's by design, and won't fix it at least for now.

**Closed by qinxuye** 2019-11-15 07:43 UTC
Labels: mod: tensor, type: bug
