### ISSUE TITLE
Fail to import Mars modules: libc++ not loaded

### ISSUE THREAD

**Issue by eitazhou** [mars-project/mars#1041] opened 2020-03-08 05:30 UTC
In my laptop(mac os catalina,10.15.3, macbook air)，mars can be installed by pip,but when I import mars in ipython, the system will show some kinds of Error. if 'import mars.dataframe as md ' , the ImportError is:dlopen(/usr/local/lib/python3.7/site-packages/mars/lib/mmh3.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libc++.1.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/mars/lib/mmh3.cpython-37m-darwin.so
  Reason: image not found ; if 'import mars.tensor as mt ',the system show:"AttributeError: type object 'mars._utils.Tokenizer' has no attribute '__reduce_cython__'". Did I miss something?

**Comment by wjsi** [comment] 2020-03-08 05:43
Please check the output of ``otool -L /usr/local/lib/python3.7/site-packages/mars/lib/mmh3.cpython-37m-darwin.so``. This issue is often caused by a conflicting libc++.
We recommend installing Mars with Miniconda which will cause fewer environment issues.

**Comment by eitazhou** [comment] 2020-03-08 08:27
thx. actually this error maybe come from dependence of pyarrow.  In requirements.txt declared pyarrow<=0.16.0 ,  but [there has a little bug ](https://github.com/apache/arrow/issues/5987)in pyarrow 0.15.1 , numpy is a build-time dependency but not declared. pyarrow 0.16.0 is ok, but can't use in mars.

**Comment by qinxuye** [comment] 2020-03-08 11:00
> thx. actually this error maybe come from dependence of pyarrow. In requirements.txt declared pyarrow<0.16.0 , but [there has a little bug ](https://github.com/apache/arrow/issues/5987)in pyarrow 0.15.1 , numpy is a build-time dependency but not declared. pyarrow 0.16.0 is ok, but can't use in mars.

Thanks, we will adapt pyarrow 0.16.0 ASAP.

**Comment by wjsi** [comment] 2020-03-15 01:22
> > thx. actually this error maybe come from dependence of pyarrow. In requirements.txt declared pyarrow<0.16.0 , but [there has a little bug ](https://github.com/apache/arrow/issues/5987)in pyarrow 0.15.1 , numpy is a build-time dependency but not declared. pyarrow 0.16.0 is ok, but can't use in mars.
> 
> Thanks, we will adapt pyarrow 0.16.0 ASAP.

The reason that we cannot use 0.16.0 is that when we slicing arrays esp. in shuffle operands, it is easy to produce empty arrays, and Plasma Store fails to store these arrays. An issue is reported to Arrow and can be traced at https://issues.apache.org/jira/browse/ARROW-8122.

**Comment by wjsi** [comment] 2020-04-21 07:48
pyarrow 0.17.0 has been released and available in pypi, and the incompatibility with Mars is now resolved. Thus I close this issue as there should be no problems with the latest pyarrow version.

**Closed by wjsi** 2020-04-21 07:48 UTC
