### ISSUE TITLE
[BUG] Unable to parallelize the toy tasks on the distributed computing cluster

### ISSUE THREAD

**Issue by anders0821** [mars-project/mars#458] opened 2019-06-15 08:47 UTC
**Describe the bug**
I run one scheduler, one web server, and two workers on two virtual machines following the steps in the GitHub README. I notice that my toy tasks cannot fully utilize all the CPU cores on two workers. It seems that only one worker is working.
![CC12CA982B41538B7E63C9B3D64FC512](https://user-images.githubusercontent.com/4899823/59549152-08f55500-8f8c-11e9-85f7-09c80aafb9f9.jpg)
(I cannot find any built-in diagnosing tools except the CPU monitor provided by the Linux OS.)
The web UI shows that both works are registered to the cluster. But only the first registered one is used. If the order of the worker registration is changed, the CPU working load is switched to another machine too.

**To Reproduce**
1. Python 3.7.3, Ubuntu 19.04
2. pymars 0.1.3
3. numpy 1.16.4, scipy 1.3.0, protobuf 3.6.1
4. No error message
5. Toy code to reproduce the error:
```
import mars.tensor as mt
from mars.session import new_session

# matmul
# D = 5000
# a_ = mt.ones((D, D), chunk_size=int(D/10))
# b_ = mt.ones((D, D), chunk_size=int(D/10))
# m1_ = mt.ones((D, D), chunk_size=int(D/10))
# m2_ = mt.ones((D, D), chunk_size=int(D/10))
# for i in range(10):
#     m1_ = mt.matmul(a_, m1_)
# for i in range(10):
#     m2_ = mt.matmul(m2_, b_)
# final_ = mt.sum(m1_) + mt.sum(m2_)

# svd
# D = 4000
# a_ = mt.ones((D, D), chunk_size=int(D/10))
# u_, s_, v_ = mt.linalg.svd(a_)
# final_ = mt.sum(u_) + mt.sum(s_) + mt.sum(v_)
# sum(a_)

# matrix plus scalar, example in the official github README
# D = 5000
# a_ = mt.ones((D, D), chunk_size=int(D/10))
# for i in range(1000):
#     a_ = a_ + 1
# final_ = mt.sum(a_)
# sum(a_)

# inner of two matrices, example in the official github README
D = 5000
a_ = mt.ones((D, D), chunk_size=int(D/10))
final_ = mt.inner(a_, a_)
# final_ = mt.sum(b_)

sess = new_session('http://172.22.167.35:7777')
final = sess.run(final_)
print(final)
```

**Expected behavior**
The working load is balanced on two workers.

**Comment by wjsi** [comment] 2019-06-15 08:55
This is caused by the operand ``ones`` as Mars tends to treat identical operands as one operand, and thus the computation graph has only one input. Try replacing ``ones`` with ``mars.tensor.random.random((size, size))`` and you will see a larger graph running distributedly.

**Comment by chineking** [comment] 2019-06-15 11:15
Let's treat the first code snippet as an example.

```python
In [9]: import mars.tensor as mt 
   ...: from mars.session import new_session 
   ...:  
   ...: # matmul 
   ...: D = 5000 
   ...: a_ = mt.ones((D, D), chunk_size=int(D/10)) 
   ...: b_ = mt.ones((D, D), chunk_size=int(D/10)) 
   ...: m1_ = mt.ones((D, D), chunk_size=int(D/10)) 
   ...: m2_ = mt.ones((D, D), chunk_size=int(D/10)) 
   ...: for i in range(10): 
   ...:     m1_ = mt.matmul(a_, m1_) 
   ...: for i in range(10): 
   ...:     m2_ = mt.matmul(m2_, b_) 
   ...: final_ = mt.sum(m1_) + mt.sum(m2_)    

In [12]: final_.visualize(tiled=True).view()
```

We will see the fine-grained graph:

![image](https://user-images.githubusercontent.com/357506/59550718-9f337600-8fa0-11e9-831c-5a006a72ece4.png)

We will find that the entire graph just rely on one node. Like @wjsi said, for the `ones` with the same size, we only generate one chunk, hence the entire graph act like this. 

For Mars execution, given an node with inputs, we will choose the worker where the inputs allocate on. Thus for the case, only one worker is leveraged. 

In order to address this problem, we have a few solutions.

1. Detect the hotspot in the graph, and distribute chunk data to all or some of workers in advance.
2. Support work stealing which is absent in Mars. The free workers can steal jobs and would not destroy the locality.

But if you want to do some test, random is better just like @wjsi  said.

**Comment by anders0821** [comment] 2019-06-15 16:08
Thank @wjsi and @chineking  for the attention. I do not think much know about the dependence of the computing graph. I use mt.ones() since it is the test code in the “Distributed” section of the README page. The mt.ones() have a parameter called chunk_size. Does this indicate that mt.ones() can be divided into chunks in some cases? According to the suggestion, I have tried random values instead. It works. The CPU time of each work increases. All workers are working now.
![1](https://user-images.githubusercontent.com/4899823/59553602-986d2900-8fc9-11e9-8bf3-1090a8871481.png)
I want to find out which operation is parallelized, the random values (really costly), the following calculations, or both of them. So I further test this:
```
D = 1000

# 1) ones data managed by mars cluster -> on one workers, run for a short time
# a_ = mt.ones((D, D), chunk_size=int(D/10))
# b_ = mt.ones((D, D), chunk_size=int(D/10))

# 2) random data managed by mars cluster -> on two workers, run for a long time
a_ = mt.random.random((D, D), chunk_size=int(D/10))
b_ = mt.random.random((D, D), chunk_size=int(D/10))

# 3) ones data provided by user -> on one workers, run for a short time
# a_ = mt.array(np.ones((D, D)).tolist(), chunk_size=int(D/10))
# b_ = mt.array(np.ones((D, D)).tolist(), chunk_size=int(D/10))

# 4) random data provided by user -> on two workers, run for a long time
# a_ = mt.array(np.random.random((D, D)).tolist(), chunk_size=int(D/10))
# b_ = mt.array(np.random.random((D, D)).tolist(), chunk_size=int(D/10))

final_ = mt.matmul(a_, b_)
```

It is a comparison between matmul of four kinds of data:
1) mt.ones()
2) mt.random.random() suggested by @wjsi  and @chineking , 
3) mt.array(np.ones(…, to show the parallelization of independent matmul.
4) mt.array(np.random.random(…, to show the parallelization of independent matmul.

The 1) and 2) shows the problem of mt.ones discussed below.
In 3) and 4), I convert the np.ndarray to mars' (const?) Tensor by mt.array() to move the data generating work out of the cluster. Both Tensor are almost the same except their contents. It is wired that the cluster knows the content of the Tensor and treat 3) and 4) differently. Can someone explain this?

Finally, is there some kind of tools or debug logs to diagnose the data storing and the job dispatch? I am very interested in the inside of the cluster. The high efficient program cannot be written down before understanding these basic rules which are not mentioned in the documents. I think chunking is almost the most fantastic feature in mars. But, many things behind data chunking are unknown. For example, the matmul of two block matrices with different chunk size is wired in common sense. The chunking state of the concatenation of two matrices with different chunk size is unknown (both function mt.matmul and mt.concatenate have no chunk_size parameter)… What is relation between the data chunking and the division of the operations?

**Comment by anders0821** [comment] 2019-06-15 20:53
I understood the tasks of matmul of two ones. The mt.ones((1000, 1000), chunk_size=int(100)) actually create 100 chunk of 100*100. These chunks are all equal. So they are merged into a single copy. The following operations like matmul may create sub-matmul and add based on the chunks. Since the chunks are equal, these sub-matmul operations are simplified into one copy too. So the final computing graph of original matmul 1000*1000 is simplified into one sub-matmul 100*100 followed by add operation. It is rapidly (1000*1000->100*100) computed on a single worker. Since there is no bug about the parallelization. This thread can be closed.

**Comment by chineking** [comment] 2019-06-16 04:10
> I understood the tasks of matmul of two ones. The mt.ones((1000, 1000), chunk_size=int(100)) actually create 100 chunk of 100*100. These chunks are all equal (checked by hash or some content based comparing?). So they are linked into a single copy. The following operations like matmul may create sub-matmul and add based on the chunks. Since the chunks are equal, these sub-matmul operations are simplified into one copy too. So the final computing graph of original matmul 1000*1000 is simplified into one sub-matmul 100*100 followed by add operation. It is rapidly (1000*1000->100*100) computed on a single worker. Since there is no bug about the parallelization. This thread can be closed.

Basically, you are right, only the creation operands like `mt.ones` or `mt.array` have `chunk_size` parameter. Mars will tile every operand that implemented in `mars.tensor`. There is a `key` property for operands, tileable objects and chunks which is calculated by other properties to indicate that if it's identical to other ones.

Yes, parallelism won't always accelerate the execution, because many factors will cost extra time, for instance, the tiling process of Mars, or the data transfering between workers. 

I think we can add some docs for the internals. I opened an issue in #460 .

I will close this issue.

**Closed by chineking** 2019-06-16 04:10 UTC
