### ISSUE TITLE
[BUG] `DataFrame.to_csv` failed

### ISSUE THREAD

**Issue by shizhiqiang007** [mars-project/mars#1938] opened 2021-01-27 13:22 UTC
使用df_to_csv()  这个api的时候总是报错，但是使用原生的pandas保存为csv不会报错：ValueError: chunks shape should be of the same length, got shape: nan, chunks: (nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan)

**Comment by wjsi** [comment] 2021-01-27 13:30
Please provide ypur code example and error stack.

**Comment by qinxuye** [comment] 2021-01-27 13:32
Seems duplicate with #1901 , it must have been addressed in 0.6.4(not released yet). You can make a verification after 0.6.4 released around this weekend.

**Comment by shizhiqiang007** [comment] 2021-01-28 06:16
> Please provide your code example and error stack. The version of Mars in use is also needed.

import time
import mars.dataframe as md

start = time.time()
df = md.read_csv("test3.csv",header=None)
df1 = df[[1,2,6]]
df1 = df1.fillna(0)
df1 = df1[df1[6]!=0]
df1 = (df1**2+2*df1)-df1*9
(df1.sort_values(by=6)).to_csv("mars.csv").execute()
end = time.time()
print("time:",end-start)

**Comment by shizhiqiang007** [comment] 2021-01-28 08:45
> Seems duplicate with #1901 , it must have been addressed in 0.6.4(not released yet). You can make a verification after 0.6.4 released around this weekend.

The interface for saving data is very common, why is there this bug

**Comment by qinxuye** [comment] 2021-01-28 09:54
> > Seems duplicate with #1901 , it must have been addressed in 0.6.4(not released yet). You can make a verification after 0.6.4 released around this weekend.
> 
> The interface for saving data is very common, why is there this bug

It's because the DataFrame to save to csv has unknown chunk shapes, unknown shape does not always exist.

Really sorry that this bug annoys you. Please wait for the release of 0.6.4 which could have resolved the problem.

**Comment by qinxuye** [comment] 2021-01-30 06:25
@shizhiqiang007 v0.6.4 is released just now, could you please try to install this version and check if this issue is resolved?

**Comment by qinxuye** [comment] 2021-02-01 06:56
@shizhiqiang007 have you confirmed that this issue has been addressed?

**Comment by qinxuye** [comment] 2021-02-04 03:05
Close it cuz no further feedback, feel free to reopen if this issue emerges again.

**Closed by qinxuye** 2021-02-04 03:05 UTC
Labels: question
